spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/Project/blog/spring_uploaded_files
  datasource: # 데이터베이스 정보 추가
    url: jdbc:h2:mem:testdb
    username : sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 에있는 쿼리를 실행하도록 하는 옵션
    defer-datasource-initialization: true
  security :
    oauth2 :
      client :
        registration:
          google:
            client-id : 797472350069-v41quue5cdst638hjk16np6ad3f33u9o.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com # 이슈발급자
  secret_key: study-springboot # 비밀키
